name: Client CI

on:
    push:
        branches: [dev, main]
        paths:
            - 'client/**'
    pull_request:
        branches: [dev, main]
        paths:
            - 'client/**'

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: npm install
              run: cd client && npm install
            - name: react build
              run: cd client && npm run build
