name: Server CI

on:
    push:
        branches: [dev, main]
        paths:
            - 'server/**'
    pull_request:
        branches: [dev, main]
        paths:
            - 'server/**'

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: npm install
              run: cd server && npm install
            - name: run server
              run: cd server && npm run lint
